/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Labour {
  'id' : bigint,
  'workType' : string,
  'dailyWage' : bigint,
  'name' : string,
  'createdAt' : Time,
  'siteId' : bigint,
  'phone' : string,
}
export interface LabourPayment {
  'id' : bigint,
  'date' : string,
  'labourId' : bigint,
  'createdAt' : Time,
  'notes' : string,
  'amount' : bigint,
}
export interface Site {
  'id' : bigint,
  'clientName' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'isActive' : boolean,
  'siteName' : string,
  'totalProjectAmount' : bigint,
  'location' : string,
  'startDate' : string,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'transactionType' : { 'miscExpense' : null } |
    { 'labourPayment' : null } |
    { 'paymentReceived' : null } |
    { 'materialPurchase' : null },
  'date' : string,
  'createdAt' : Time,
  'notes' : string,
  'paymentMode' : { 'upi' : null } |
    { 'cash' : null } |
    { 'bankTransfer' : null } |
    { 'cheque' : null },
  'siteId' : bigint,
  'amount' : bigint,
}
export interface UserProfile {
  'userId' : string,
  'name' : string,
  'email' : string,
  'pinHash' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLabour' : ActorMethod<[bigint, string, string, string, bigint], bigint>,
  'addLabourPayment' : ActorMethod<[bigint, string, bigint, string], bigint>,
  'addTransaction' : ActorMethod<
    [
      bigint,
      { 'miscExpense' : null } |
        { 'labourPayment' : null } |
        { 'paymentReceived' : null } |
        { 'materialPurchase' : null },
      string,
      bigint,
      string,
      { 'upi' : null } |
        { 'cash' : null } |
        { 'bankTransfer' : null } |
        { 'cheque' : null },
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSite' : ActorMethod<[string, string, string, string, bigint], bigint>,
  'deactivateSite' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    { 'totalReceived' : bigint, 'totalGiven' : bigint, 'activeSites' : bigint }
  >,
  'getLabourBySite' : ActorMethod<[bigint], Array<Labour>>,
  'getLabourPayments' : ActorMethod<[bigint], Array<LabourPayment>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getRecentTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'getSiteById' : ActorMethod<[bigint], [] | [Site]>,
  'getSites' : ActorMethod<[], Array<Site>>,
  'getTransactionsBySite' : ActorMethod<[bigint], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPin' : ActorMethod<[string], undefined>,
  'updateLabour' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'updateSite' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    undefined
  >,
  'verifyPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];