/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'pinHash' : IDL.Text,
});
export const Time = IDL.Int;
export const Labour = IDL.Record({
  'id' : IDL.Nat,
  'workType' : IDL.Text,
  'dailyWage' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'siteId' : IDL.Nat,
  'phone' : IDL.Text,
});
export const LabourPayment = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'labourId' : IDL.Nat,
  'createdAt' : Time,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Variant({
    'miscExpense' : IDL.Null,
    'labourPayment' : IDL.Null,
    'paymentReceived' : IDL.Null,
    'materialPurchase' : IDL.Null,
  }),
  'date' : IDL.Text,
  'createdAt' : Time,
  'notes' : IDL.Text,
  'paymentMode' : IDL.Variant({
    'upi' : IDL.Null,
    'cash' : IDL.Null,
    'bankTransfer' : IDL.Null,
    'cheque' : IDL.Null,
  }),
  'siteId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Site = IDL.Record({
  'id' : IDL.Nat,
  'clientName' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'siteName' : IDL.Text,
  'totalProjectAmount' : IDL.Nat,
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLabour' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addLabourPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTransaction' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'miscExpense' : IDL.Null,
          'labourPayment' : IDL.Null,
          'paymentReceived' : IDL.Null,
          'materialPurchase' : IDL.Null,
        }),
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Variant({
          'upi' : IDL.Null,
          'cash' : IDL.Null,
          'bankTransfer' : IDL.Null,
          'cheque' : IDL.Null,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSite' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deactivateSite' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalReceived' : IDL.Nat,
          'totalGiven' : IDL.Nat,
          'activeSites' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLabourBySite' : IDL.Func([IDL.Nat], [IDL.Vec(Labour)], ['query']),
  'getLabourPayments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LabourPayment)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getRecentTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getSiteById' : IDL.Func([IDL.Nat], [IDL.Opt(Site)], ['query']),
  'getSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
  'getTransactionsBySite' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPin' : IDL.Func([IDL.Text], [], []),
  'updateLabour' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateSite' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'verifyPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'pinHash' : IDL.Text,
  });
  const Time = IDL.Int;
  const Labour = IDL.Record({
    'id' : IDL.Nat,
    'workType' : IDL.Text,
    'dailyWage' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'siteId' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const LabourPayment = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'labourId' : IDL.Nat,
    'createdAt' : Time,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Variant({
      'miscExpense' : IDL.Null,
      'labourPayment' : IDL.Null,
      'paymentReceived' : IDL.Null,
      'materialPurchase' : IDL.Null,
    }),
    'date' : IDL.Text,
    'createdAt' : Time,
    'notes' : IDL.Text,
    'paymentMode' : IDL.Variant({
      'upi' : IDL.Null,
      'cash' : IDL.Null,
      'bankTransfer' : IDL.Null,
      'cheque' : IDL.Null,
    }),
    'siteId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Site = IDL.Record({
    'id' : IDL.Nat,
    'clientName' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'siteName' : IDL.Text,
    'totalProjectAmount' : IDL.Nat,
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLabour' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addLabourPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTransaction' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'miscExpense' : IDL.Null,
            'labourPayment' : IDL.Null,
            'paymentReceived' : IDL.Null,
            'materialPurchase' : IDL.Null,
          }),
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Variant({
            'upi' : IDL.Null,
            'cash' : IDL.Null,
            'bankTransfer' : IDL.Null,
            'cheque' : IDL.Null,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deactivateSite' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalReceived' : IDL.Nat,
            'totalGiven' : IDL.Nat,
            'activeSites' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLabourBySite' : IDL.Func([IDL.Nat], [IDL.Vec(Labour)], ['query']),
    'getLabourPayments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LabourPayment)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getRecentTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getSiteById' : IDL.Func([IDL.Nat], [IDL.Opt(Site)], ['query']),
    'getSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
    'getTransactionsBySite' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPin' : IDL.Func([IDL.Text], [], []),
    'updateLabour' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateSite' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'verifyPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };