/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Labour {
    id: bigint;
    workType: string;
    dailyWage: bigint;
    name: string;
    createdAt: Time;
    siteId: bigint;
    phone: string;
}
export interface Transaction {
    id: bigint;
    transactionType: Variant_miscExpense_labourPayment_paymentReceived_materialPurchase;
    date: string;
    createdAt: Time;
    notes: string;
    paymentMode: Variant_upi_cash_bankTransfer_cheque;
    siteId: bigint;
    amount: bigint;
}
export type Time = bigint;
export interface Site {
    id: bigint;
    clientName: string;
    owner: Principal;
    createdAt: Time;
    isActive: boolean;
    siteName: string;
    totalProjectAmount: bigint;
    location: string;
    startDate: string;
}
export interface UserProfile {
    userId: string;
    name: string;
    email: string;
    pinHash: string;
}
export interface LabourPayment {
    id: bigint;
    date: string;
    labourId: bigint;
    createdAt: Time;
    notes: string;
    amount: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_miscExpense_labourPayment_paymentReceived_materialPurchase {
    miscExpense = "miscExpense",
    labourPayment = "labourPayment",
    paymentReceived = "paymentReceived",
    materialPurchase = "materialPurchase"
}
export enum Variant_upi_cash_bankTransfer_cheque {
    upi = "upi",
    cash = "cash",
    bankTransfer = "bankTransfer",
    cheque = "cheque"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLabour(siteId: bigint, name: string, phone: string, workType: string, dailyWage: bigint): Promise<bigint>;
    addLabourPayment(labourId: bigint, date: string, amount: bigint, notes: string): Promise<bigint>;
    addTransaction(siteId: bigint, transactionType: Variant_miscExpense_labourPayment_paymentReceived_materialPurchase, date: string, amount: bigint, notes: string, paymentMode: Variant_upi_cash_bankTransfer_cheque): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createSite(siteName: string, clientName: string, location: string, startDate: string, totalProjectAmount: bigint): Promise<bigint>;
    deactivateSite(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        totalReceived: bigint;
        totalGiven: bigint;
        activeSites: bigint;
    }>;
    getLabourBySite(siteId: bigint): Promise<Array<Labour>>;
    getLabourPayments(labourId: bigint): Promise<Array<LabourPayment>>;
    getMyProfile(): Promise<UserProfile | null>;
    getRecentTransactions(limit: bigint): Promise<Array<Transaction>>;
    getSiteById(id: bigint): Promise<Site | null>;
    getSites(): Promise<Array<Site>>;
    getTransactionsBySite(siteId: bigint): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setPin(pinHash: string): Promise<void>;
    updateLabour(id: bigint, name: string, phone: string, workType: string, dailyWage: bigint): Promise<void>;
    updateSite(id: bigint, siteName: string, clientName: string, location: string, startDate: string, totalProjectAmount: bigint): Promise<void>;
    verifyPin(pinHash: string): Promise<boolean>;
}
import type { Site as _Site, Time as _Time, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLabour(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLabour(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLabour(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addLabourPayment(arg0: bigint, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLabourPayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLabourPayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTransaction(arg0: bigint, arg1: Variant_miscExpense_labourPayment_paymentReceived_materialPurchase, arg2: string, arg3: bigint, arg4: string, arg5: Variant_upi_cash_bankTransfer_cheque): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_variant_n2(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_variant_n2(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSite(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSite(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSite(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deactivateSite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateSite(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        totalReceived: bigint;
        totalGiven: bigint;
        activeSites: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLabourBySite(arg0: bigint): Promise<Array<Labour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabourBySite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabourBySite(arg0);
            return result;
        }
    }
    async getLabourPayments(arg0: bigint): Promise<Array<LabourPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabourPayments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabourPayments(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentTransactions(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentTransactions(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentTransactions(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteById(arg0: bigint): Promise<Site | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteById(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteById(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSites(): Promise<Array<Site>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSites();
            return result;
        }
    }
    async getTransactionsBySite(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsBySite(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsBySite(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setPin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPin(arg0);
            return result;
        }
    }
    async updateLabour(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLabour(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLabour(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateSite(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSite(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSite(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async verifyPin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPin(arg0);
            return result;
        }
    }
}
function from_candid_Transaction_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Site]): Site | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: {
        miscExpense: null;
    } | {
        labourPayment: null;
    } | {
        paymentReceived: null;
    } | {
        materialPurchase: null;
    };
    date: string;
    createdAt: _Time;
    notes: string;
    paymentMode: {
        upi: null;
    } | {
        cash: null;
    } | {
        bankTransfer: null;
    } | {
        cheque: null;
    };
    siteId: bigint;
    amount: bigint;
}): {
    id: bigint;
    transactionType: Variant_miscExpense_labourPayment_paymentReceived_materialPurchase;
    date: string;
    createdAt: Time;
    notes: string;
    paymentMode: Variant_upi_cash_bankTransfer_cheque;
    siteId: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_variant_n11(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        createdAt: value.createdAt,
        notes: value.notes,
        paymentMode: from_candid_variant_n12(_uploadFile, _downloadFile, value.paymentMode),
        siteId: value.siteId,
        amount: value.amount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    miscExpense: null;
} | {
    labourPayment: null;
} | {
    paymentReceived: null;
} | {
    materialPurchase: null;
}): Variant_miscExpense_labourPayment_paymentReceived_materialPurchase {
    return "miscExpense" in value ? Variant_miscExpense_labourPayment_paymentReceived_materialPurchase.miscExpense : "labourPayment" in value ? Variant_miscExpense_labourPayment_paymentReceived_materialPurchase.labourPayment : "paymentReceived" in value ? Variant_miscExpense_labourPayment_paymentReceived_materialPurchase.paymentReceived : "materialPurchase" in value ? Variant_miscExpense_labourPayment_paymentReceived_materialPurchase.materialPurchase : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cash: null;
} | {
    bankTransfer: null;
} | {
    cheque: null;
}): Variant_upi_cash_bankTransfer_cheque {
    return "upi" in value ? Variant_upi_cash_bankTransfer_cheque.upi : "cash" in value ? Variant_upi_cash_bankTransfer_cheque.cash : "bankTransfer" in value ? Variant_upi_cash_bankTransfer_cheque.bankTransfer : "cheque" in value ? Variant_upi_cash_bankTransfer_cheque.cheque : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_miscExpense_labourPayment_paymentReceived_materialPurchase): {
    miscExpense: null;
} | {
    labourPayment: null;
} | {
    paymentReceived: null;
} | {
    materialPurchase: null;
} {
    return value == Variant_miscExpense_labourPayment_paymentReceived_materialPurchase.miscExpense ? {
        miscExpense: null
    } : value == Variant_miscExpense_labourPayment_paymentReceived_materialPurchase.labourPayment ? {
        labourPayment: null
    } : value == Variant_miscExpense_labourPayment_paymentReceived_materialPurchase.paymentReceived ? {
        paymentReceived: null
    } : value == Variant_miscExpense_labourPayment_paymentReceived_materialPurchase.materialPurchase ? {
        materialPurchase: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_upi_cash_bankTransfer_cheque): {
    upi: null;
} | {
    cash: null;
} | {
    bankTransfer: null;
} | {
    cheque: null;
} {
    return value == Variant_upi_cash_bankTransfer_cheque.upi ? {
        upi: null
    } : value == Variant_upi_cash_bankTransfer_cheque.cash ? {
        cash: null
    } : value == Variant_upi_cash_bankTransfer_cheque.bankTransfer ? {
        bankTransfer: null
    } : value == Variant_upi_cash_bankTransfer_cheque.cheque ? {
        cheque: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
